[2022-12-01T07:37:21.261+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count manual__2022-12-01T07:37:17.119491+00:00 [queued]>
[2022-12-01T07:37:21.283+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count manual__2022-12-01T07:37:17.119491+00:00 [queued]>
[2022-12-01T07:37:21.283+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T07:37:21.283+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-01T07:37:21.283+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T07:37:21.312+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): count> on 2022-12-01 07:37:17.119491+00:00
[2022-12-01T07:37:21.325+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_start_dag', 'count', 'manual__2022-12-01T07:37:17.119491+00:00', '--job-id', '1179', '--raw', '--subdir', 'DAGS_FOLDER/start_dag.py', '--cfg-path', '/tmp/tmp6p_zink4']
[2022-12-01T07:37:21.329+0000] {standard_task_runner.py:83} INFO - Job 1179: Subtask count
[2022-12-01T07:37:21.319+0000] {standard_task_runner.py:55} INFO - Started process 1461 to run task
[2022-12-01T07:37:21.448+0000] {task_command.py:376} INFO - Running <TaskInstance: a_start_dag.count manual__2022-12-01T07:37:17.119491+00:00 [running]> on host 3859ff78a683
[2022-12-01T07:37:21.583+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_start_dag
AIRFLOW_CTX_TASK_ID=count
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T07:37:17.119491+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-01T07:37:17.119491+00:00
[2022-12-01T07:37:21.645+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/start_dag.py", line 17, in count_r
    return len(r["Game Number"])
TypeError: string indices must be integers
[2022-12-01T07:37:21.659+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_start_dag, task_id=count, execution_date=20221201T073717, start_date=20221201T073721, end_date=20221201T073721
[2022-12-01T07:37:21.681+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1179 for task count (string indices must be integers; 1461)
[2022-12-01T07:37:21.716+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-01T07:37:21.758+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
