[2022-11-30T12:22:38.029+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count manual__2022-11-30T12:22:35.229360+00:00 [queued]>
[2022-11-30T12:22:38.042+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count manual__2022-11-30T12:22:35.229360+00:00 [queued]>
[2022-11-30T12:22:38.042+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T12:22:38.042+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T12:22:38.042+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T12:22:38.060+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): count> on 2022-11-30 12:22:35.229360+00:00
[2022-11-30T12:22:38.068+0000] {standard_task_runner.py:55} INFO - Started process 10640 to run task
[2022-11-30T12:22:38.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_start_dag', 'count', 'manual__2022-11-30T12:22:35.229360+00:00', '--job-id', '1064', '--raw', '--subdir', 'DAGS_FOLDER/start_dag.py', '--cfg-path', '/tmp/tmpuu0lirh5']
[2022-11-30T12:22:38.074+0000] {standard_task_runner.py:83} INFO - Job 1064: Subtask count
[2022-11-30T12:22:38.178+0000] {task_command.py:376} INFO - Running <TaskInstance: a_start_dag.count manual__2022-11-30T12:22:35.229360+00:00 [running]> on host ab28c0b87467
[2022-11-30T12:22:38.308+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_start_dag
AIRFLOW_CTX_TASK_ID=count
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T12:22:35.229360+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T12:22:35.229360+00:00
[2022-11-30T12:22:38.350+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/start_dag.py", line 16, in count_r
    return r["Game Number"]
TypeError: string indices must be integers
[2022-11-30T12:22:38.376+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_start_dag, task_id=count, execution_date=20221130T122235, start_date=20221130T122238, end_date=20221130T122238
[2022-11-30T12:22:38.400+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1064 for task count (string indices must be integers; 10640)
[2022-11-30T12:22:38.448+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T12:22:38.473+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
