[2022-11-29T13:18:41.786+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count_row manual__2022-11-29T13:18:41.149460+00:00 [queued]>
[2022-11-29T13:18:41.798+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.count_row manual__2022-11-29T13:18:41.149460+00:00 [queued]>
[2022-11-29T13:18:41.799+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T13:18:41.799+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T13:18:41.799+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T13:18:41.816+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): count_row> on 2022-11-29 13:18:41.149460+00:00
[2022-11-29T13:18:41.823+0000] {standard_task_runner.py:55} INFO - Started process 15242 to run task
[2022-11-29T13:18:41.827+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_start_dag', 'count_row', 'manual__2022-11-29T13:18:41.149460+00:00', '--job-id', '1000', '--raw', '--subdir', 'DAGS_FOLDER/start_dag.py', '--cfg-path', '/tmp/tmp0uhpmqrn']
[2022-11-29T13:18:41.828+0000] {standard_task_runner.py:83} INFO - Job 1000: Subtask count_row
[2022-11-29T13:18:41.952+0000] {task_command.py:376} INFO - Running <TaskInstance: a_start_dag.count_row manual__2022-11-29T13:18:41.149460+00:00 [running]> on host ab28c0b87467
[2022-11-29T13:18:42.088+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_start_dag
AIRFLOW_CTX_TASK_ID=count_row
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T13:18:41.149460+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T13:18:41.149460+00:00
[2022-11-29T13:18:42.802+0000] {logging_mixin.py:137} INFO - Количество строк исключая заголовок = 10000
[2022-11-29T13:18:42.802+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/start_dag.py", line 13, in count_r
    xcom.push(answer = row_sum)
NameError: name 'xcom' is not defined
[2022-11-29T13:18:42.809+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_start_dag, task_id=count_row, execution_date=20221129T131841, start_date=20221129T131841, end_date=20221129T131842
[2022-11-29T13:18:42.825+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1000 for task count_row (name 'xcom' is not defined; 15242)
[2022-11-29T13:18:42.860+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T13:18:42.877+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
